{% set name = "biom-format" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b47e54282ef13cddffdb00aea9183a87175a2372c91a915259086a3f444c42f4

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - biom = biom.cli:cli

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - click
    - scipy >=0.13.0
    - future >=0.16.0
    - pandas >=0.19.2
    - six >=1.10.0

test:
  imports:
    - biom
    - biom._filter
    - biom._transform
    - biom._subsample
  commands:
    - biom --help

about:
  home: http://biom-format.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Biological Observation Matrix (BIOM) format'
  dev_url: https://github.com/biocore/biom-format

extra:
  recipe-maintainers:
    - synapticarbors
    - wasade
