{% set name = "biom-format" %}
{% set version = "2.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d8813f84f7a79ee8c367e6ef57e154a121198b3979b81c74e6514668b756827

build:
  number: 0
  entry_points:
    - biom = biom.cli:cli

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - click
    - future >=0.16.0
    - pandas >=0.20.0
    - pyqi  # [py2k]
    - scipy >=0.13.0
    - six >=1.10.0

test:
  imports:
    - biom
    - biom._filter
    - biom._transform
    - biom._subsample
  commands:
    - biom --help

about:
  home: http://biom-format.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Biological Observation Matrix (BIOM) format'
  dev_url: https://github.com/biocore/biom-format

extra:
  recipe-maintainers:
    - synapticarbors
    - wasade
    - nsoranzo
    - thermokarst
