schema_version: 1

context:
  name: biom-format
  version: 2.1.17

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 8e3fa07a432b3f6d5c3cad491ef1f27b18d10fc151ca2d223761be4f0b050479

build:
  number: 1
  script:
    env:
      USE_CYTHON: "1"
    content: python -m pip install . --no-deps --no-build-isolation -vv
  python:
    entry_points:
      - biom = biom.cli:cli

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy >=1.9.2
        - h5py >=3.0.0
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy >=1.9.2
    - h5py >=3.0.0
  run:
    - python
    - click
    - pandas >=0.20.0
    - scipy >=1.3.1
    - h5py >=3.0.0
    - numpy >=1.9.2

tests:
  - python:
      imports:
        - biom
        - biom._filter
        - biom._transform
        - biom._subsample
      pip_check: true
  - script:
      - biom --help

about:
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: Biological Observation Matrix (BIOM) format
  homepage: http://biom-format.org/
  repository: https://github.com/biocore/biom-format

extra:
  recipe-maintainers:
    - synapticarbors
    - wasade
    - nsoranzo
