appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: afSfHpQVZNS2plG04luldq2B7tXVCPVqEBT0gEFjNhYQoLwiMc309NX3Q82Y9hlTDOXnHz6zTxyIjj+Lqge79D1duG7LwaBXsluVj/IKfF6n+LAyFqwxlD0SM9lozSqPPDxd5EFoWquxUfzE52XDcudEaRDud5AHWJ2rLr1w9tg+c+Y9Z6WUyyEYk8eSACW/mcy+uzEN+3wDMCLjLzVEHJGWTRBVuQzyKKXw9LNSKGTez1WfyZtB+18N9zUE908TNUJGYtWVNLJr0ut1i+9i4iLVFonn8kgKSCdR5mn9zj2+7BQgoZhKdPTHh1mJRUIDUstL1vxTEYgPptSLgc1h2zzfIcUy4icq9FbRuKmHJVRm1qwbPXUhbAfNE3XB/FdxtkTza1tUyVIQLwI8gzTgQ1qE2LDe0F2xyfvBuE8YFvEW8n5P9ZrXgFNLZTgCqbsyqigYL2OyKRGzKUteXbSi0RH/tj14un5vSPd729MVu+cv5dIVRO+IISluOCHywakXcLJLCTecoMhAyUoymy6UNh+bNDp5Vw/ekempvbfnFcAgJle3hPWWyfNHm8looMkZ6Nj64s/esbdA8FOTMq724YCHhxbzzyAVb29QbYZvN4TJbMMcMKEEGTOIjwWJ9WSS3hMSXvCuV5/fwqIcAXwp3TlRswFbq1h+dUiDUnlNIvI=}
